import { Job, Application, Institution, Notification, DashboardStats } from "@/types";

export const mockInstitutions: Institution[] = [
  {
    id: "1",
    type: "masjid",
    name: "Masjid Al-Noor",
    address: "123 Main St",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    contactPerson: "Mohammed Ali",
    phone: "+91 9876543210",
    email: "info@masjidalnoor.com",
  },
  {
    id: "2",
    type: "madrasa",
    name: "Darul Uloom Academy",
    address: "456 Park Ave",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    contactPerson: "Abdul Rahman",
    phone: "+91 9876543211",
    email: "info@darululoom.com",
  },
  {
    id: "3",
    type: "masjid",
    name: "Jama Masjid Trust",
    address: "789 Ring Road",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    contactPerson: "Khalid Hassan",
    phone: "+91 9876543212",
    email: "info@jamamasjid.com",
  },
];

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Imam",
    categoryId: "religious",
    role: "Imam",
    description: "We are looking for a qualified Imam to lead prayers and provide spiritual guidance to our congregation.",
    responsibilities: "Lead 5 daily prayers, deliver Friday Khutbah, provide counseling, teach Quran classes.",
    salary: "₹30,000 - ₹45,000/month",
    accommodationAvailable: true,
    foodAvailable: true,
    location: "Mumbai, Maharashtra",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    experienceRequired: "3+ years",
    educationRequired: "Alim/Fazil degree",
    vacancyCount: 1,
    joiningDate: "2025-02-01",
    status: "active",
    institutionId: "1",
    institution: mockInstitutions[0],
    applicationsCount: 12,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "2",
    title: "Arabic Teacher",
    categoryId: "education",
    role: "Arabic Teacher",
    description: "Seeking an experienced Arabic language teacher for our Madrasa students.",
    responsibilities: "Teach Arabic grammar, literature, and communication skills to students aged 10-18.",
    salary: "₹20,000 - ₹30,000/month",
    accommodationAvailable: false,
    foodAvailable: false,
    location: "Delhi",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    experienceRequired: "2+ years",
    educationRequired: "B.A. Arabic / Alim",
    vacancyCount: 2,
    joiningDate: "2025-01-15",
    status: "active",
    institutionId: "2",
    institution: mockInstitutions[1],
    applicationsCount: 8,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "3",
    title: "Muazzin",
    categoryId: "religious",
    role: "Muazzin",
    description: "We are looking for a Muazzin with a good voice and proper Tajweed knowledge.",
    responsibilities: "Call Azan for 5 daily prayers, assist Imam in mosque activities.",
    salary: "₹15,000 - ₹20,000/month",
    accommodationAvailable: true,
    foodAvailable: true,
    location: "Hyderabad, Telangana",
    city: "Hyderabad",
    state: "Telangana",
    country: "India",
    experienceRequired: "1+ years",
    educationRequired: "Basic education",
    vacancyCount: 1,
    joiningDate: "2025-01-20",
    status: "active",
    institutionId: "3",
    institution: mockInstitutions[2],
    applicationsCount: 5,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "4",
    title: "Hafiz Teacher",
    categoryId: "education",
    role: "Hafiz Teacher",
    description: "Looking for a Hafiz-e-Quran to teach Hifz classes to students.",
    responsibilities: "Teach Quran memorization, monitor progress, conduct revision sessions.",
    salary: "₹25,000 - ₹35,000/month",
    accommodationAvailable: true,
    foodAvailable: false,
    location: "Pune, Maharashtra",
    city: "Pune",
    state: "Maharashtra",
    country: "India",
    experienceRequired: "Fresh/Experienced",
    educationRequired: "Hafiz-e-Quran",
    vacancyCount: 3,
    joiningDate: "2025-02-15",
    status: "active",
    institutionId: "1",
    institution: mockInstitutions[0],
    applicationsCount: 15,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockApplications: Application[] = [
  {
    id: "1",
    jobId: "1",
    seekerId: "user1",
    status: "shortlisted",
    appliedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
  },
  {
    id: "2",
    jobId: "2",
    seekerId: "user1",
    status: "under_review",
    appliedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[1],
  },
  {
    id: "3",
    jobId: "3",
    seekerId: "user1",
    status: "applied",
    appliedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[2],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    title: "Application Shortlisted!",
    message: "Masjid Al-Noor has shortlisted your application for Senior Imam position.",
    read: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    type: "application",
  },
  {
    id: "2",
    title: "New Job Alert",
    message: "A new Imam position matching your profile has been posted in Mumbai.",
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    type: "job",
  },
  {
    id: "3",
    title: "Application Under Review",
    message: "Darul Uloom Academy is reviewing your application for Arabic Teacher.",
    read: true,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    type: "application",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalJobs: 48,
  activeJobs: 32,
  totalApplications: 156,
  newApplications: 12,
  totalUsers: 1240,
  userGrowth: 18,
};
